### ISSUE TITLE
Complex names on SELECTs throw Sizzle Error

### ISSUE THREAD

**Issue by MatthewCallis** [jzaefferer/jquery-validation#1603] opened 2015-10-05 18:09 UTC
When you go to change a select / drop down with a complex name a Sizzle error is thrown. Tested in Chrome 45, 47, Safari 9.0. Using v1.14.0.

```
Uncaught Error: Syntax error, unrecognized expression: label[for='custom-data[1]['key']'], label[for='custom-data[1]['key']'] *

Stack Trace:
Sizzle.error                  @  jquery2.js:1459
Sizzle.tokenize               @  jquery2.js:2076
Sizzle.compile                @  jquery2.js:2447
Sizzle.select                 @  jquery2.js:2537
Sizzle                        @  jquery2.js:856
Sizzle.matches                @  jquery2.js:1397
jQuery.filter                 @  jquery2.js:2673
winnow                        @  jquery2.js:2656
jQuery.fn.extend.filter       @  jquery2.js:2705
$.extend.errorsFor            @  jquery.validate.js:860
$.extend.prepareElement       @  jquery.validate.js:604
$.extend.element              @  jquery.validate.js:435
$.extend.defaults.onfocusout  @  jquery.validate.js:267
delegate                      @  jquery.validate.js:381
jQuery.event.dispatch         @  jquery2.js:4436
elemData.handle               @  jquery2.js:4122
jQuery.event.trigger          @  jquery2.js:4351
jQuery.event.simulate         @  jquery2.js:4653
handler                       @  jquery2.js:4781
```

https://jsfiddle.net/matthewcallis/zbbusgve/

**Comment by staabm** [comment] 2015-10-05 18:23
Shouldnt your fieldname be `name="custom-data[0][key]"` instead of `name="custom-data[0]['key']"`?

**Comment by MatthewCallis** [comment] 2015-10-05 18:30
@staabm that unfortunately doesn't work when the key has a space in it, such as `user input`.

**Comment by staabm** [comment] 2015-10-08 16:50
duplicate of https://github.com/jzaefferer/jquery-validation/issues/1504 but no solution yet.

**Comment by Arkni** [comment] 2015-10-08 21:12
@staabm 
I think this can be fixed by escaping the single and double quotes found `name`, something like this:
```diff
diff --git a/src/core.js b/src/core.js
index cca489e..aa1c958 100644
--- a/src/core.js
+++ b/src/core.js
@@ -841,9 +841,16 @@ $.extend( $.validator, {
 		},
 
 		errorsFor: function( element ) {
-			var name = this.idOrName( element ),
-				describer = $( element ).attr( "aria-describedby" ),
-				selector = "label[for='" + name + "'], label[for='" + name + "'] *";
+			var describer = $( element ).attr( "aria-describedby" ),
+				name, selector;
+
+			name = this.idOrName( element )
+					// escape double-quotes
+					.replace( /"/g, "\\\"" )
+					// escape single-quotes
+					.replace( /'/g, "\\'" );
+
+			selector = "label[for='" + name + "'], label[for='" + name + "'] *";
 
 			// aria-describedby should directly reference the error element
 			if ( describer ) {
```

**Comment by staabm** [comment] 2015-10-08 21:14
I guess we dont need to escape double quotes

**Comment by Arkni** [comment] 2015-10-08 21:23
Yes, you're right. (updated the diff)

**Comment by staabm** [comment] 2015-10-08 21:38
@Arkni would you submit a PR supported by a unit test?

**Comment by staabm** [comment] 2015-10-08 21:40
Maybe also the square brackets are a problem...

**Comment by Arkni** [comment] 2015-10-08 22:05
>@Arkni would you submit a PR supported by a unit test?

Will do that tomorrow :)
 
>Maybe also the square brackets are a problem...

I don't think so, I already tested the case in #1504 but can't reproduce the issue, so I don't think there is a need for escaping the brackets.

**Comment by Arkni** [comment] 2015-10-09 12:17
@staabm 
Just wondering about the unit test,  what do you expect to see tested ?

I'm thinking in doing the following:

**HTML**
```html
<form id="testForm">
	<!-- test id/name containing single quotes -->
	<input name="testForm['text input']" id="testForm['text input']" required>
</form>
```

**JS**
```js
test( "test id/name containing single quotes", function() {
	var v = $( "#testForm" ).validate(),
		field = $( "#testForm\\[\\'text input\\'\\]" );

	v.form();
	equal( v.numberOfInvalids(), 1, "There is only one invalid element" );
	equal( v.isValidElement( field[ 0 ] ), false, "The element should be invalid" );
	equal( v.invalidElements()[ 0 ], field[ 0 ], "The element should be invalid" );
});
```

Your thoughts ?

**Comment by staabm** [comment] 2015-10-09 12:20
@Arkni most important thing is, that your unit test runs into the error reported by @MatthewCallis in the initial ticket and it no longer errors with your patch applied.

The suggested changes look good without running them.

Easiest thing for you and me would be, you open a PR which in the 1 commit contains the failing test and in a followup-commit the patched lines, so the build will be green again.

**Comment by Arkni** [comment] 2015-10-09 13:37
> Easiest thing for you and me would be, you open a PR which in the 1 commit contains the failing test and in a followup-commit the patched lines, so the build will be green again (so I can see in travis-ci, that your test runs in the error the user initially reported).

Sounds good to me, will do that soon :)

**Closed** 2015-10-09 17:56 UTC
Labels: Bug
