### ISSUE TITLE
resetForm not handle the success option

### ISSUE THREAD

**Issue by DreamTear** [jzaefferer/jquery-validation#1856] opened 2016-09-07 05:40 UTC
when i use success option,then use the resetForm method, success optiion not be handled
eg:
````javascript
$("#captchaform").validate({
		rules: {
			captcha: {
				required: true,
				remote: "process.php"
			}
		},
		messages: {
			captcha: "Correct captcha is required. Click the captcha to generate a new one"
		},
		submitHandler: function() {
			alert("Correct captcha!");
		},
		success: function(label) {
			label.addClass("valid").text("Valid captcha!")
		},
		onkeyup: false
	});
````

**Comment by staabm** [comment] 2016-09-07 06:55
I am not sure what you mean. do you expect the success-callback beeing invoked on form-reset?

**Comment by DreamTear** [comment] 2016-09-07 07:09
the success method changed the label style,then call resetForm method,the label style not reset

**Comment by staabm** [comment] 2016-09-07 15:21
In case you do markup-changes in the success handler, you have to do the inverse also on your own. the plugin itself does not keep track of your markup changes.

I guess highlight/unhighlight is what you are after.
[1] https://jqueryvalidation.org/validate/#highlight

I will close this issue now, as it is a question, not a bug.
feel free to ask furhter questions anyway.

**Closed by staabm** 2016-09-07 15:21 UTC
