### ISSUE TITLE
Cannot clear validation errors when jquery.form library is included - only reset entire form.

### ISSUE THREAD

**Issue by dave-newson** [jzaefferer/jquery-validation#1540] opened 2015-08-03 06:47 UTC
We've got some custom integration between jquery-validation and an Ajax form. We also use jquery.form in some of our codebase.

We want to be able to reset ONLY the form errors, which traditionally we would do with a call to $validator.resetForm();

Unfortunately, when you have the jquery.form library included, jquery-validation's resetForm method also calls $.fn.resetForm. This causes the form data itself to be reset.

Due to this, there's no way to reset just the form errors without also resetting the form content with this library installed. I also can't see a way to opt-out of this assumptive integration.

See fiddle: http://jsfiddle.net/hwz1c37t/

The obvious answer is "don't use jquery.form" but unfortunately that's not an option.  I'd much prefer it if there was a method exclusively for resetting validation, or a toggle to opt in/out of the jquery.form integration.

**Comment by Arkni** [comment] 2015-11-07 23:40
Just came across this issue and found that the problem is caused by these lines [/src/core.js#L479-L481](https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L479-L481):
```js
if ( $.fn.resetForm ) {
	$( this.currentForm ).resetForm();
}
```

The jquery.form library define already this function to reset the form data, see [jquery.form.js#L1211-L1222](https://github.com/malsup/form/blob/master/jquery.form.js#L1211-L1222):
```js
/**
 * Resets the form data.  Causes all form elements to be reset to their original value.
 */
$.fn.resetForm = function() {
    return this.each(function() {
        // guard against an input with the name of 'reset'
        // note that IE reports the reset function as an 'object'
        if (typeof this.reset == 'function' || (typeof this.reset == 'object' && !this.reset.nodeType)) {
            this.reset();
        }
    });
};
```
So, the plugin will call this function first to wipe the form data, then reset the error messages.

Also, there is already a unit test which assert that the form was cleared when _jquery form plugin_ is included, see https://github.com/jzaefferer/jquery-validation/blob/master/test/test.js#L840.

**_So this is the intended behavior, not a bug._**

But even after knowing this behavior is intended, there is a question that needs an answer:
>_"why the three lines above (the first link) are added in the first place?"_.

I tracked down the commits in order to answer it, and found that these lines are already there when jzafferer committed the whole project for the first time back in _**Aug 1, 2009**_

So only @jzaefferer can answer this question.

**Comment by Arkni** [comment] 2015-11-07 23:49
I forgot to mention that you can work around this issue by overriding the `resetForm` function of `jquery form plugin`, what I did is:
```js
$.fn.resetForm = $.noop;
```

**Comment by dave-newson** [comment] 2015-11-09 22:40
@Arkni thanks for the explanation. I too came to the conclusion about those lines of code during my original debugging. I also agree this appears to be the intended behaviour when integrated with jquery.form.

We use jquery.form in a variety of places, so just wholesale noop'ing jquery.form's resetForm function isn't really an option. It's also equivalently hacky as my original money-patch, so I don't see much of a gain.

My issue, is I'd rather that jquery-validation didn't assume I want this integrated functionality when the two libraries are on the same page, or at least let me disable the integration (which would be backwards compat).

In case I've missed something and there's a better way to do this, here's why I'm down this path:
I'm trying to use jquery-validation to accept a validation response from the server (JSON), which maps errors messages to fields.  When I re-submit the form, I want to use jquery-validation to clear any remaining validation errors.
This is all working, bar the fact that I can't clear the validation errors using jquery-validation without jquery.form also being called to reset the form data.

Again, thanks for taking the time to look at this.

**Comment by Arkni** [comment] 2015-11-09 23:14
> @Arkni thanks for the explanation.

You're welcome :)

> We use jquery.form in a variety of places, so just wholesale noop'ing jquery.form's resetForm function isn't really an option. It's also equivalently hacky as my original money-patch, so I don't see much of a gain.

I see what you mean, I also thought about that and looking for another workaround.

>In case I've missed something and there's a better way to do this, here's why I'm down this path:
I'm trying to use jquery-validation to accept a validation response from the server (JSON), which maps errors messages to fields. When I re-submit the form, I want to use jquery-validation to clear any remaining validation errors.
This is all working, bar the fact that I can't clear the validation errors using jquery-validation without jquery.form also being called to reset the form data.

I hope this integration was removed from the first time. Until this happens, I'm using an other ugly solution (_Sorry I forgot to came back to mention it here_):
```js
// Back-up the jquery.form's resetForm function
var resetForm = $.fn.resetForm;

// Delete it so jquery-validate will not find it
delete $.fn.resetForm;

// Reset the validation errors
validator.resetForm();

// And then restore it
$.fn.resetForm = resetForm;
```

**Comment by staabm** [comment] 2015-11-10 08:18
I guess a proper integration fix for you could also be

```js
var oldValidatorResetForm = validator.resetForm;
validator.resetForm = function() {
  // Back-up the jquery.form's resetForm function
  var resetForm = $.fn.resetForm;

  // Delete it so jquery-validate will not find it
  delete $.fn.resetForm;

  // Reset the validation errors
  oldValidatorResetForm();

  // And then restore it
  $.fn.resetForm = resetForm;
};
```

so you only need to do it once and you can use the API of jquery-validate as suggested in the samples etc.

**Closed** 2015-11-10 08:21 UTC

**Comment by dave-newson** [comment] 2015-11-12 22:35
@staabm, I'm OK with the close. Your solution does monkey-patch a routine around the issue, which would probably work for my basic use case.

I think this could be BC by simply having the integration with jquery.form as opt-out; simply wrapping the functionality in an if which defaults to enabled unless I override it in my validator settings.

I'm happy to come up with a PR for this myself, provided you think that's a suitable solution?
Are there any other spots where jquery.form comes into play?

**Comment by staabm** [comment] 2015-11-12 22:45
Since this is the only issue I am aware of and we try to reduce options/settings in the validator, I am not willing to add a new option/setting for such an edge case.

In case we can find a small BC patch I am open for it though
