### ISSUE TITLE
Validation on input type number not working on Google Chrome

### ISSUE THREAD

**Issue by sachingadagi** [jzaefferer/jquery-validation#1663] opened 2015-12-12 14:31 UTC
<h2><b> This breaks in Google chrome only </b></h2>
when an **input** element with _type=number_ is validated against 
``` required: true, digits:true``` and non-numeric values are supplied,  the plugin breaks.
Fiddle
[https://jsfiddle.net/5nx2qgu6/1/]

Thanks & Regards,
SG

**Comment by staabm** [comment] 2015-12-19 13:21
Not 100% sure, but it seems we only have a manual test for this case?
https://github.com/jzaefferer/jquery-validation/blob/d09a5ee19944c756311e6021871ae45f51901fd6/test/number.html

Is your error reproducible using the number.html file?

**Comment by Arkni** [comment] 2015-12-19 13:40
Duplicate of #1514 and #1611

**Comment by staabm** [comment] 2015-12-19 14:24
Will be handled in https://github.com/jzaefferer/jquery-validation/issues/1514 then, thx.

**Closed** 2015-12-19 14:23 UTC
Labels: Bug
