### ISSUE TITLE
Bootstrap-FileStyle causes jQuery-Validation to always return True

### ISSUE THREAD

**Issue by JungleGenius** [jzaefferer/jquery-validation#1693] opened 2016-01-19 05:12 UTC
Hi,

First of all thanks for a fantastic bit of code. I love using  jQuery-Validation on my forms.

However, I'm running into a bit of an issue. I'm using the Laravel 5 Javascript Validation package here:
"proengsoft/laravel-jsvalidation" that is basically a wrapper around "jzaefferer/jquery-validation".

If a Bootstrap-FileStyle input is located inside a form that I am validating using the jQuery Validation Plugin the validation always returns true regardless of any form errors. I'm not sure if I should be asking you or the Bootstrap-FileStyle folks so I am posting here as well.

I'm trying to track this all down but I thought I would open a ticket and see if you have any insights.

Thanks!

**Comment by staabm** [comment] 2016-01-19 14:28
@JungleGenius could you create a reduced jsfiddle which demonstrates the issue?

**Comment by staabm** [comment] 2016-02-05 20:28
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:28 UTC
Labels: NO FIDDLE

**Comment by JungleGenius** [comment] 2016-04-28 23:35
Hi, My apologies for not following up with a reply much sooner. As it turns out this was due to a conflict with the Google Maps JavaScript library. As long as you don't use both in/on the same page the Bootstrap Files Style works as it should. Not sure why or how, but I did not need a upload dialog on the same page as my Google Map so I never went far enough to find out why.
