### ISSUE TITLE
Version 1.14.0 breaks number validation.

### ISSUE THREAD

**Issue by simone91** [jzaefferer/jquery-validation#1611] opened 2015-10-12 12:43 UTC
Try to enter a letter in this sample form and submit it.
https://jsfiddle.net/2x9bbnu9/1/
https://jsfiddle.net/Lgkbok58/1/

Version 1.13.1 works correctly.
Version 1.14.0 does not report the error.

**Comment by Arkni** [comment] 2015-10-12 20:27
Duplicate of #1514

As I can tell, this is caused by this commit: 2ad0ca82daf091fc692018b38e01e896fd304015

**Closed** 2015-10-13 10:30 UTC
