### ISSUE TITLE
Summernote compatibility - "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by bennybee** [jzaefferer/jquery-validation#1875] opened 2016-10-10 12:35 UTC
<h3>Subject of the issue</h3>
Validating a form containing a Summernote WYSIWYG field causes error.

<h3>Your environment</h3>
<ul>
<li>Version of jquery-validate: 1.15.1</li>
<li>Version of summernote: 0.8.2</li>
<li>Browser: Chrome 54.0.2840.71</li>
</ul>

<h3>Steps to reproduce</h3>
Validate form containing Summernote field<br>
Type inside form then blur / trigger validation<br>
<a href="https://jsfiddle.net/benember/b0xchnnp/6/">https://jsfiddle.net/benember/b0xchnnp/6/</a>

<h3>Expected behaviour</h3>
Field validates

<h3>Actual behaviour</h3>
Console error:

`jquery.validate.js:1014 <br>
Uncaught TypeError: Cannot read property 'replace' of undefined`

I Think this is related to:
#1785
Which should have been merged into 1.15.1

**Comment by staabm** [comment] 2016-12-01 15:19
Will release a new version today, please double check this will be fixed using it.

**Comment by bennybee** [comment] 2016-12-02 10:42
Just tested with 1.16.0-pre and still got the same error

**Comment by r0lan2** [comment] 2017-01-11 21:42
Actually I am getting the same error as @bennybee, I am using summernote v0.8.2 with asp.net mvc 5.

![summernote](https://cloud.githubusercontent.com/assets/777801/21867598/a4ef26fc-d82d-11e6-87d8-b48704aa0bcc.png)

**Comment by Arkni** [comment] 2017-01-15 01:41
@bennybee @r0lan2 
See the following code. I explained a little what happened and what should be done in order to make `Summernote` to work with `jQuery-validation`.

```js
var v = $('#myForm').validate({
  // Ignore all hidden elements except your `textarea` element. Also, you have to
  // ignore the div that `Summernote` uses to hold your entered data (which is also a
  // content editable div with no name) because this plugin will try to check it on blur.
  // and because it has no name, the error shown in your capture will pop up (the
  // `escapeCssMeta` method escapes the name/id of an element, and in this case
  // an undefined value was passed to it, hence the error message).
  //
  // The div has the following class `.note-editable .panel-body` that we can use to
  // exclude it from validation
  ignore: ":hidden:not(#summernote),.note-editable.panel-body"
});

var myElement = $('#summernote');

myElement.summernote({
  // See: http://summernote.org/deep-dive/
  callbacks: {
    // Register the `onChnage` callback in order to listen to the changes of the
    // Summernote editor. You can also use the event `summernote.change` to handle
    // the change event as follow:
    //   myElement.summernote()
    //     .on("summernote.change", function(event, contents, $editable) {
    //       // ...
    //     });
    onChange: function(contents, $editable) {
      // Note that at this point, the value of the `textarea` is not the same as the one
      // you entered into the summernote editor, so you have to set it yourself to make
      // the validation consistent and in sync with the value.
      myElement.val(myElement.summernote('isEmpty') ? "" : contents);

      // You should re-validate your element after change, because the plugin will have
      // no way to know that the value of your `textarea` has been changed if the change
      // was done programmatically.
      v.element(myElement);
    }
  }
});
```

**Comment by aszx0413** [comment] 2017-01-19 01:53
1.16.0 still got the error

**Comment by Arkni** [comment] 2017-01-20 22:21
@aszx0413 please provide a reproducible example

**Comment by staabm** [comment] 2017-01-28 12:28
Will close for now because of inactivity. Feel free to ask further questions/provide furhter information regarding this topic here. We can re-open if required.

**Closed by staabm** 2017-01-28 12:28 UTC

**Comment by umutesen** [comment] 2017-02-06 13:52
Is there any solutions to this problem?

**Comment by Arkni** [comment] 2017-02-06 13:58
Please see the solution I put in my previous [comment](https://github.com/jquery-validation/jquery-validation/issues/1875#issuecomment-272667183).

**Comment by paulgabronis** [comment] 2017-02-24 12:51
Same error with trumbowyg editor.

**Comment by MrChriZ** [comment] 2017-03-01 19:04
Getting this with NicEdit

**Comment by MrChriZ** [comment] 2017-03-01 19:26
https://jsfiddle.net/whp51ncf/

**Comment by HochunNN** [comment] 2017-03-06 15:32
@Arkni in the first place, thank you for the kind answer. Do you happen to know how to solve "Cannot read property 'nodeName' of undefined" as well? I tried the code you wrote above but couldn't solve the problem. Thanks in advance.

**Comment by Arkni** [comment] 2017-03-07 14:57
Hi @HochunNN 
Can you provide a [`JSFiddle`](https://jsfiddle.net/) that demonstrates the error. That way I will have a good look at the error and its source.

Thanks

**Comment by HochunNN** [comment] 2017-03-07 16:02
@Arkni Arkni Thank you for the reply. I figured it out myself! actually it was really simple. I was using old version and as I changed it with latest one, the error disappeared!

**Comment by JeffreyChan** [comment] 2017-03-21 07:09
why i am still getting this error in asp.net mvc 5 with latest version?
`                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CommentText">
                            Remark <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea name="CommentText" id="CommentText"></textarea>
                        </div>
                    </div>`
here is my js code:

` var v = $('#fromRiskUnit').validate({
                // Ignore all hidden elements except your `textarea` element. Also, you have to
                // ignore the div that `Summernote` uses to hold your entered data (which is also a
                // content editable div with no name) because this plugin will try to check it on blur.
                // and because it has no name, the error shown in your capture will pop up (the
                // `escapeCssMeta` method escapes the name/id of an element, and in this case
                // an undefined value was passed to it, hence the error message).
                //
                // The div has the following class `.note-editable .panel-body` that we can use to
                // exclude it from validation
                ignore: ":hidden:not(#CommentText),.note-editable.panel-body"
            });

            $('#CommentText')
                .summernote({
                    focus: true,
                    height: 150,
                    codemirror: {
                        theme: 'united'
                    }
                });`
I am not validation this input, if the input has value, then I focus the other input, the error will throw.
![image](https://cloud.githubusercontent.com/assets/5321225/24136119/47eb6dca-0e48-11e7-8390-a7ff65f1867f.png)

**Comment by jeremycook** [comment] 2017-07-12 15:37
@JeffreyChan @MrChriZ @paulgabronis @Arkni I use this script to tell the validator to ignore Summernote elements. It can be tweaked to ignore elements generated by other HTML editors.

    $('form').each(function () {
        if ($(this).data('validator'))
            $(this).data('validator').settings.ignore = ".note-editor *";
    });

**Comment by Arkni** [comment] 2017-07-12 22:49
@jeremycook 
You can do the same using [`jQuery.validator.setDefaults()`](https://jqueryvalidation.org/jQuery.validator.setDefaults/):
```js
// This will set `ignore` for all validation calls
jQuery.validator.setDefaults({
  // This will ignore all hidden elements alongside `contenteditable` elements
  // that have no `name` attribute
  ignore: ":hidden, [contenteditable='true']:not([name])"
});
```

**Comment by FahaoTang** [comment] 2017-09-30 05:25
Hi all
I just want make one addition update to this issue:
if you are using bootstrap 4 and obviously panel has been replaced by card.
So one of the line in the resolution can be now replaced:
`ignore: ":hidden:not(#summernote),.note-editable.panel-body"`
with 
`ignore: ":hidden:not(#summernote),.note-editable.card-block"`

**Comment by eman1986** [comment] 2018-03-27 15:01
I see this error still and I'm still using Bootstrap 3, nothing above was working with me, I'm using the latest version of both libraries

**Comment by peca11** [comment] 2018-06-10 15:12
Same here!

**Comment by fanomena** [comment] 2018-08-15 18:19
Getting this with froala WYSIWYG Editor

**Comment by blue-eyed-devil** [comment] 2018-12-07 11:30
> @jeremycook
> You can do the same using [`jQuery.validator.setDefaults()`](https://jqueryvalidation.org/jQuery.validator.setDefaults/):
> 
> ```js
> // This will set `ignore` for all validation calls
> jQuery.validator.setDefaults({
>   // This will ignore all hidden elements alongside `contenteditable` elements
>   // that have no `name` attribute
>   ignore: ":hidden, [contenteditable='true']:not([name])"
> });
> ```

This works like a charm also for emojionearea. Without :hidden ofcourse.

**Comment by SoloOne** [comment] 2019-01-08 06:59
> ### Subject of the issue
> Validating a form containing a Summernote WYSIWYG field causes error.
> ### Your environment
> * Version of jquery-validate: 1.15.1
> * Version of summernote: 0.8.2
> * Browser: Chrome 54.0.2840.71
> 
> ### Steps to reproduce
> Validate form containing Summernote field
> Type inside form then blur / trigger validation
> https://jsfiddle.net/benember/b0xchnnp/6/
> ### Expected behaviour
> Field validates
> ### Actual behaviour
> Console error:
> `jquery.validate.js:1014 <br> Uncaught TypeError: Cannot read property 'replace' of undefined`
> 
> I Think this is related to:
> #1785
> Which should have been merged into 1.15.1

do you have fixed this issue,I tried all solutions of the comments,but doesn't work

**Comment by sunsande** [comment] 2020-09-02 20:06
> 
> 
> @jeremycook
> You can do the same using [`jQuery.validator.setDefaults()`](https://jqueryvalidation.org/jQuery.validator.setDefaults/):
> 
> ```js
> // This will set `ignore` for all validation calls
> jQuery.validator.setDefaults({
>   // This will ignore all hidden elements alongside `contenteditable` elements
>   // that have no `name` attribute
>   ignore: ":hidden, [contenteditable='true']:not([name])"
> });
> ```
It works only on submit. The ignore does not work for onfocusout :(

**Comment by furcan** [comment] 2020-10-28 23:09
Please change
from

```js
escapeCssMeta: function( string ) {
    return string.replace( /([\\!"#$%&'()*+,./:;<=>?@\[\]^`{|}~])/g, "\\$1" );
},
```

to

```js
escapeCssMeta: function( string ) {
    return (string||'').replace( /([\\!"#$%&'()*+,./:;<=>?@\[\]^`{|}~])/g, "\\$1" );
},
```

Thanks.

**Comment by borakayalar** [comment] 2021-02-17 10:39
> Hi all
> I just want make one addition update to this issue:
> if you are using bootstrap 4 and obviously panel has been replaced by card.
> So one of the line in the resolution can be now replaced:
> `ignore: ":hidden:not(#summernote),.note-editable.panel-body"`
> with
> `ignore: ":hidden:not(#summernote),.note-editable.card-block"`

#If you are using bootstrap 4, pls use "card-block" instead of "panel-body"

**Comment by pencsi** [comment] 2022-02-08 10:27
I checked my summernote structure in html and I didn't find any panel-body or card-block with note-editable
for me help to delete this part in that line:

ignore: ":hidden:not(#summernote),.note-editable"
this worked for me absolutly no more undifiend problem
