### ISSUE TITLE
Number validation cross culture

### ISSUE THREAD

**Issue by MrGrabazu** [jzaefferer/jquery-validation#1577] opened 2015-09-11 15:37 UTC
I don't think it's an issue, but I've faced some difficulties to post a form with a decimal field in it.
Because I'm french and my decimal separator is a comma, jQuery Validation stop the post because my decimal is not a valid number.
It's not true, it's a well formatted number according to my culture specifications.
I searched and all the solutions I have found are to install jquery globalize (with his dependencies, cdrl.js) in my project to solve this matter, and other solutions that I don't want to.
I think I've found a better way to solve it by replacing the RegExp in the jquery validation source for the number validation method from 

    ^-?(?:\d+|\d{1,3}(?:,\d{3})+)?(?:\.\d+)?$

to 

    ^-?(?:\d+|\d{1,3}(?:,\d{3})+)?(?:(\.|,)\d+)?$

which is almost the same.

It work fine for all this decimal number format : 

    149.99
    149,99
    1,149.99

So, would it not be simpler to replace the english culture oriented number validation RegExp by this global culture oriented one ??

**Comment by staabm** [comment] 2015-09-12 07:26
Your regexp doesnt work because it allows numbers with several commas in it like 1,400,90. 

You should define a custom method which only matches the number format you like to support or redefine the number method from outside. See e.g. http://stackoverflow.com/questions/17444985/jquery-validate-and-mask-for-decimal-and-thousands-separator

AFAIR we dont support this feature natively.

**Comment by staabm** [comment] 2015-09-12 07:28
Duplicate of #188 - should integrate Globalize to solve this properly.

**Closed by staabm** 2015-09-12 07:28 UTC

**Comment by MrGrabazu** [comment] 2015-09-14 13:14
I think this one doesn't validate 1,149,99

    ^-?((?:\d+|\d{1,3}(?:,\d{3})+)?(?:\.\d+)|(?:\d+|\d{1,3}(?:\s?\d{3})+)?(?:,\d+))?$

Include Globalize is not the good choice for an application that runs into one single language. It's an haevy client side library just to recognize comma instead of point on client side validation.. Just because the default regex present in the jquery validation library is not enough complete. There is not thousand ways to write a decimal number I think.
