### ISSUE TITLE
contenteditable element bug

### ISSUE THREAD

**Issue by liamwang** [jzaefferer/jquery-validation#1784] opened 2016-05-15 03:44 UTC
Here is the html demo:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <form action="#" method="post">
        <input type="text" name="id" />
        <div contenteditable="true" style="border:1px solid #ccc;height:100px;"></div>
    </form>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.3.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.js"></script>
    <script>
        $('form').validate();
    </script>
</body>
</html>
```
Run this html and focus in contenteditable element, then there is an error in source code here:

![2016-05-15_112312](https://cloud.githubusercontent.com/assets/5000396/15271863/46ad380a-1a90-11e6-984e-cd4e34a58347.png)

**Comment by staabm** [comment] 2016-05-15 05:03
Thx for the report. Looks like a duplicate of https://github.com/jzaefferer/jquery-validation/issues/1729

**Closed by staabm** 2016-05-15 05:03 UTC
