### ISSUE TITLE
Date validation

### ISSUE THREAD

**Issue by stephenmuecke** [jzaefferer/jquery-validation#1792] opened 2016-05-30 07:50 UTC
`date` validation use the following

    return this.optional(element) || !/Invalid|NaN/.test(new Date(value).toString());

If `value` is an invalid date (say) '30/30/2008' then in Chrome, it will return `false` (`new Date('30/30/2000');` returns `Invalid date`), but in FireFox, it will return `true` (`new Date('30/30/2000');` returns '29th June 2010', a valid date, but not the same date as that being validated).

Not only is the result of validation inconsistent across browsers, but an invalid date is considered valid (I note this is currently the [documented behavior](https://jqueryvalidation.org/date-method))

Refer [this fiddle](https://jsfiddle.net/cs4npjsz/2/) for a possible alternative for validation of dates - by creating a new date from the numeric components of the value and comparing it with the value returned by `new Date(value)`.

Note the fiddle also include a value for the date format which could be added as an option to the validator so that dates in different cultures could also be validated.

**Comment by staabm** [comment] 2016-05-30 13:24
this issue is a duplicate of https://github.com/jzaefferer/jquery-validation/issues/1787.

in a nutshell: the `date` method will be marked as deprecated. you should use e.g. `dateISO` instead.

Feel free to ask further followup question, I will close the ticket for now.

**Closed by staabm** 2016-05-30 13:24 UTC

**Comment by stephenmuecke** [comment] 2016-05-30 23:32
@staabm,  Will `jquery.validate.unobtrusive.js` used in asp.net-mvc also be modified to add the correct rules?

**Comment by staabm** [comment] 2016-05-31 05:58
This file is not part of this repos and it is not developed by this dev team.
