### ISSUE TITLE
Issues while using jquery validate with dojo

### ISSUE THREAD

**Issue by krishnakumar-m** [jzaefferer/jquery-validation#1620] opened 2015-10-23 01:42 UTC
My application requires use of jquery and dojo. Facing an issue while using jquery.validate version 1.14 , while initialising validator. Conflicts are shown with define function. Dojo define is being used instead of jquery define.

**Comment by staabm** [comment] 2015-10-23 09:09
@krishnakumar-m could you show us a jsfiddle which demonstrates the error? We the give information we cannot improve on what we dont know :-).

**Comment by staabm** [comment] 2016-02-05 20:23
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:23 UTC
Labels: NO FIDDLE
