### ISSUE TITLE
validation not fire on textbox in ie and firefox on following senario

### ISSUE THREAD

**Issue by kite57** [jzaefferer/jquery-validation#1678] opened 2016-01-01 05:04 UTC
hello,

i have 2 textbox,
now i am enter some text on 1st text box and go to 2nd text box using mouse click on 2nd textbox

so validation fire and it is showing correct value in 1st textbox using true sign

now i am enter some text on 2nd textbox and then click on 1st textbox so validation fire for 2nd textbox and is showing correct value for 2nd textbox using true sign

now i am at 1st textbox and just select 2nd textbox entered value[not click on 2nd textbox]  directly using mouse selection and press delete so my textbox have no value, so issue is still true sign is there... that shold be gone if i am clearing value for textbox.

can you help me to sort out this issue.

**Comment by staabm** [comment] 2016-01-30 18:58
Please provide a jsfiddle which demonstrates your problem. Otherwise its really hard to help you

**Comment by staabm** [comment] 2016-02-05 20:24
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:24 UTC
Labels: NO FIDDLE
