### ISSUE TITLE
browserify and jquery-validation

### ISSUE THREAD

**Issue by Maxim-Chugaev** [jzaefferer/jquery-validation#1834] opened 2016-08-07 18:09 UTC
package.json

```javascript
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "deploy": "gh-pages -d ./dest"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-browserify": "^0.5.1",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-jade": "^1.1.0",
    "gulp-markdown": "^1.2.0",
    "gulp-stylus": "^2.5.0",
    "markdown": "^0.5.0"
  },
  "dependencies": {
    "jquery": "^3.1.0",
    "jquery-validation": "^1.15.1"
  }
}

```
gulp task

```javascript
gulp.task('js', ()=>{

	gulp.src('./src/js/app.js')
        .pipe(browserify({
          insertGlobals : true
        }))
        .pipe(gulp.dest('./dest/js'))

});
```
require jquery and jquery-validation

```javascript
'use strict';

window.$ = window.jQuery = require('jquery');
require('jquery-validation');
```
browser console
```javascript
$.validator // undefined
```

**Comment by staabm** [comment] 2016-08-07 20:46
Duplicate of https://github.com/jzaefferer/jquery-validation/issues/1829

**Closed by staabm** 2016-08-07 20:46 UTC
