### ISSUE TITLE
Dist folder missing 1.15.1 VS 2015

### ISSUE THREAD

**Issue by jrock2004** [jzaefferer/jquery-validation#1895] opened 2016-11-18 12:49 UTC
I have a developer who does a `bower install` and when jquery-validate downloads there is no dist folder. When I try on my machine it downloads the dist folder. The user is using Visual studio 2015 so maybe it has to do with that? Could Visual Studio be caching something? Any help would be appreciated.

**Comment by ramedey** [comment] 2016-11-18 15:29
Same problem here. I also tried installing the package in another folder outside VS 2015, and the dist folder is also missing.

Therefore, this problem has nothing to do with VS 2015

**Comment by Arkni** [comment] 2016-11-18 15:54
Try clearing the cache of bower and re-install the package

**Comment by ramedey** [comment] 2016-11-18 17:24
That solved the problem for me. Thanks!

**Comment by staabm** [comment] 2016-12-01 14:59
So, can we close this issue?

**Comment by staabm** [comment] 2016-12-01 15:38
duplicate of https://github.com/jzaefferer/jquery-validation/issues/1877

**Closed by staabm** 2016-12-01 15:38 UTC
