### ISSUE TITLE
Remote dont work with add Rules

### ISSUE THREAD

**Issue by YanMagale** [jzaefferer/jquery-validation#1631] opened 2015-11-03 17:04 UTC
Hi everyone.

Using this code after validate declaration, the method remote dont work and dont call my file with ajax:

This link for the code: http://jsfiddle.net/nepqLg3f/

**Comment by Arkni** [comment] 2015-11-03 21:02
I just tested `rules( "add", { ... } )` to add the `remote` rule and it's working as expected.
See working example: http://jsfiddle.net/Arkni/8500cda0/

Also, the link you provided shows only the code you're using to add the remote method. You have to provide an example that we can follow to reproduce the problem.

**Comment by YanMagale** [comment] 2015-11-04 01:06
Sorry @Arkni, really should have put all the code i am using.

This link for the full code: http://jsfiddle.net/eg0sLhgL/

**Comment by Arkni** [comment] 2015-11-04 01:29
Any chance to provide a _demo_ so we can see which part causes the problem ?

to mock remote calls, use `jsfiddle` echo's service as in the following code:
```js
    remote: {
        url: "/echo/html/",
        type: "POST",
        data: {
            html: "false",
            delay: .5
        }
    },
```

**Comment by Arkni** [comment] 2015-11-14 20:50
@YanMagale 
Did you get a chance to create a demo so we can see which part causes the problem ?

**Comment by YanMagale** [comment] 2015-11-15 01:30
Yes @Arkni , i want.

This code is being used on a project in the company. I'll create a demo in JSFiddlle and will post the link in here.

**Comment by staabm** [comment] 2016-02-05 20:27
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:27 UTC
Labels: NO FIDDLE
