### ISSUE TITLE
Validate verifies the dynamic addition of form？

### ISSUE THREAD

**Issue by zhangangs** [jzaefferer/jquery-validation#1654] opened 2015-11-24 02:16 UTC
I dynamically added a validate, form can not work, do you have this solution?

**Comment by Arkni** [comment] 2015-11-24 22:00
Please provide a [jsfidlle](http://jsfiddle.net/) ?

**Comment by staabm** [comment] 2016-02-05 20:27
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:27 UTC
Labels: NO FIDDLE
