### ISSUE TITLE
"a.validator.methods[d] is undefined"

### ISSUE THREAD

**Issue by iki789** [jzaefferer/jquery-validation#1686] opened 2016-01-14 07:49 UTC
I'm trying to make the <input type="file" name="file"> not required but I get a a.validator.methods[d] is undefined in my console.Everything works fine if file:{required: is true. But in my case, a file is not required.

I tried using ignore: ".ignore" with file:{required:true and <input type="file" name="file" class="ignore">. It still validates on submit. And if I set file:{required: to false then I still get a a.validator.methods[d] is undefined error in console.

I have these files included:

<script src="../javascripts/jquery.validation.js"></script>
<script src="../javascripts/jquery.validation.additional.js"></script>

$('#message').validate({
      ignore: "",
      rules: {
          message:{required: true,},
          file:{required:false, accept: "png|jpe?g|gif", filesize: 1048576 }
          },
        messages:{
            message:"Please type your message",
            file:{required:"File is required", accept: "Hello"},
        },  
});

**Comment by staabm** [comment] 2016-01-30 18:47
Please provide a jsfiddle which demonstrates the problem

**Comment by staabm** [comment] 2016-02-05 20:24
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:24 UTC
Labels: NO FIDDLE
