### ISSUE TITLE
resetForm conflicts with other plugins

### ISSUE THREAD

**Issue by franksl** [jzaefferer/jquery-validation#1859] opened 2016-09-09 12:41 UTC
Hi,
When using this plugin and the jquery forms plugin (http://malsup.com/jquery/form/) there is a problem when calling the resetForm function.
Basically when doing this:
```
var validator = $( "#myform" ).validate();
validator.resetForm();
```

the resetForm() from the forms plugin gets called inside the call to validator.resetForm().

I think the problem lies in the first lines of the resetForm() method:
```
// http://jqueryvalidation.org/Validator.resetForm/
resetForm: function() {
	if ( $.fn.resetForm ) {
		$( this.currentForm ).resetForm();
	}
```
As the resetForm() from the forms plugin is defined as $.fn.resetForm the validate plugin calls that function before doing anything else and the form gets cleared. 
It's my opinion that function declarations in the forms plugin are wrong and dangerous but maybe a small fix here can make the two plugins live together.
thanks,
Frank

**Comment by Arkni** [comment] 2016-09-09 13:44
Duplicate of #1540

**Comment by staabm** [comment] 2016-10-02 08:40
Closing because duplicate. Feel free to discuss here further though.

**Closed** 2016-10-02 08:39 UTC
