### ISSUE TITLE
Validate and focus on error tabs

### ISSUE THREAD

**Issue by mtran21** [jzaefferer/jquery-validation#1688] opened 2016-01-15 22:20 UTC
How do I set focus on the bootstrap tab that has required field when submit button is clicked?

**Comment by staabm** [comment] 2016-01-30 18:49
The information provided is not enough to help you.

Whats your exact problem? Please provide a jsfiddle which demonstrates your problem

**Comment by staabm** [comment] 2016-02-05 20:27
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:27 UTC
Labels: NO FIDDLE
