### ISSUE TITLE
Localization unobtrusive

### ISSUE THREAD

**Issue by SanteR1** [jzaefferer/jquery-validation#1736] opened 2016-03-09 19:58 UTC
Please help me! (MVC 5, c#)
I connected in such order...
`    <script src="@Url.Content("~/Scripts/jquery-2.2.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/globalize.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/localization/messages_ru.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.globalize.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>`
or
`    <script src="@Url.Content("~/Scripts/jquery-2.2.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/globalize.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/localization/messages_ru.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.globalize.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>`
But localization of error messages doesn't work for me

**Comment by staabm** [comment] 2016-03-12 11:45
Please provide more information what the problem is and how to reproduce. At best provide a reduced fiddle which shows your issue

**Comment by SanteR1** [comment] 2016-03-13 10:19
I use asp.net mvc 5, js
What else detail information I need to add for the description of a problem, please tell?

![localization error message js](https://cloud.githubusercontent.com/assets/13267230/13728107/b163dc48-e91d-11e5-8721-132648bb4663.png)

**Comment by SanteR1** [comment] 2016-03-13 12:34
Hello, I test file jquery.validate.unobtrusive.js (rename to txt for attach)
[jquery.validate.unobtrusive.txt](https://github.com/jzaefferer/jquery-validation/files/170958/jquery.validate.unobtrusive.txt)
in the line 212 - message: message,
I replace to - message: "",
Then error message localization ...

**You can make changes to your library what it would clean off messages the created jquery.validate.unobtrusive?
Many probably face it when using asp.net mvc 5**

And one more test
https://jsfiddle.net/SanteR1/p54vravj/
If clear `data-val-required="The field Название is required"`
to
`data-val-required=""`
and run jsfiddle test then error message is localization to russian (or in any other localization, depending on connection of message_##.js)

**Comment by staabm** [comment] 2016-03-13 12:44
Where did you get jquery.validate.unobstrusive? This lib is not part of our project, I guess?

**Comment by SanteR1** [comment] 2016-03-13 12:48
Yes, this Microsoft lib for asp.net MVC (7 292 815 Downloads)
https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Validation/

**Comment by Arkni** [comment] 2016-03-13 14:59
Maybe this `Stackoverflow` question can help: http://stackoverflow.com/questions/34995115/jquery-validation-localization

**Comment by SanteR1** [comment] 2016-03-13 15:08
There suggest to use the resource file, and it isn't convenient when there is already such library with different localization. 
To do and translate into different languages and to add all this to the project, it how many excess operation...

**Comment by Arkni** [comment] 2016-03-13 15:22
I'm not a `.NET` guy, but including the localization file after loading `jquery-validate` is the right way to do it.
One problem is why it doesn't work when used with the unobtrusive validation. You might need to file an issue in their issue tracker: https://github.com/aspnet/jquery-validation-unobtrusive

**Comment by staabm** [comment] 2016-03-13 15:56
I close this issue now, feel free to discuss further

**Closed by staabm** 2016-03-13 15:56 UTC
Labels: NO FIDDLE
