### ISSUE TITLE
Set Defaults stopped working

### ISSUE THREAD

**Issue by attiqeurrehman** [jzaefferer/jquery-validation#1566] opened 2015-09-01 15:41 UTC
Hi,

I have recently did an upgrade of jQuery and jQuery Validation to the latest version of both. But this caused my defaults to stop working(validation is working) on some pages even though all pages share the same master page (where code is placed).

Here's the code:

```javascript
$.validator.setDefaults({
                    highlight: function (element) {
                        console.log('highlight');
                        $(element).closest('.form-group').addClass('has-error');
                    },
                    unhighlight: function (element) {
                        console.log('unhighlight');
                        $(element).closest('.form-group').removeClass('has-error');
                    },
                    errorElement: 'span',
                    errorClass: 'help-block',
                    errorPlacement: function (error, element) {
                        console.log('errorPlacement');
                        if (element.parent('.input-group').length) {
                            error.insertAfter(element.parent());
                        } else {
                            if ($(element).parent().prop("tagName") == "LI") {
                                error.insertAfter(element.parent().parent());
                            } else if ($(element).next().next().prop("tagName") == "SPAN") {
                                error.insertAfter($(element).next().next());
                            } else {
                                error.insertAfter(element);
                            }
                        }
                    }
                });

It goes into the plugin code but defaults are not set. Any pointers as to where can I look?

Thanks,
Attiqe

**Comment by staabm** [comment] 2015-09-01 21:27
May I guess that you are using the updated jQuery version in noConflict mode?

Could you please tell us exactly which versions of both libs you are using? Any errors? Which version worked correctly before?

**Comment by attiqeurrehman** [comment] 2015-09-02 09:44
I am using jQuery v 2.1.4 and jQuery Validation v 1.14.0, no error and previously I used jQuery 2.0.3 and jQuery Validation 1.13.1.

**Comment by johnnymm** [comment] 2015-09-04 04:11
same here. errorPlacement inside setDefaults is not called.

**Comment by johnnymm** [comment] 2015-09-04 04:23
seems errorPlacement inside setDefaults is not called

**Comment by staabm** [comment] 2015-09-04 18:04
Did you make sure that the lib is not loaded twice?

**Comment by attiqeurrehman** [comment] 2015-09-04 18:07
I am not sure how to check it. I have only wrote them onetime.

On Fri, Sep 4, 2015 at 11:04 PM, Markus Staab <notifications@github.com>
wrote:

> Did you make sure that the lib is not loaded twice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jzaefferer/jquery-validation/issues/1566#issuecomment-137807636>
> .
>



-- 
Attiqe Ur Rehman

**Comment by staabm** [comment] 2015-10-21 15:04
@attiqeurrehman any news? Did you got to the cause of the issue?

**Comment by staabm** [comment] 2016-02-05 20:31
Closing because no more feedback

**Closed by staabm** 2016-02-05 20:31 UTC
