### ISSUE TITLE
first focus into an input,cannot validate

### ISSUE THREAD

**Issue by xiongsisi** [jzaefferer/jquery-validation#1624] opened 2015-10-28 04:35 UTC
onfocusin: function( element ) {

i write 'this.lastElement = element;' in the fun

**Comment by staabm** [comment] 2015-10-28 08:12
@xiongsisi please provide a jsfiddle which reproduces your issue. with this little information we cannot help you.

**Comment by xiongsisi** [comment] 2015-10-28 09:12
i expect the library can validate when i first focus into one input .
![second focus into the input](https://cloud.githubusercontent.com/assets/13955666/10784075/f2775a40-7d96-11e5-8fe7-7bd678d42165.png)

![image](https://cloud.githubusercontent.com/assets/13955666/10784054/d4f12834-7d96-11e5-951e-1365a63fbe32.png)
![first focus into one input no validate](https://cloud.githubusercontent.com/assets/13955666/10784064/e1a2ad46-7d96-11e5-8a9d-0d48eb557db2.png)

**Comment by xiongsisi** [comment] 2015-10-28 09:14
first picture is i second focus into the input,last one is the first focus.

**Comment by staabm** [comment] 2015-10-28 09:30
by default a elements get validated when it loses focus. Therefore I think it doesnt work on the 2nd focus but on the first blur.

do you say, you want to start validation of the field on focus - even if the user did not start typing yet?

**Comment by xiongsisi** [comment] 2015-10-28 09:37
yes,that is what i mean

**Comment by xiongsisi** [comment] 2015-10-28 09:39
i think this is a bug,because i trigger onkeyup event,the library should start validation

**Comment by staabm** [comment] 2015-10-28 09:41
@xiongsisi I dont think it makes sense to validate a field on 1st focus, but maybe it somehow makes sense in your app.

did you try invoking `validator.element(...)` in a focus event handler?

see http://jqueryvalidation.org/Validator.element/

**Comment by staabm** [comment] 2015-10-28 09:42
> i think this is a bug,because i trigger onkeyup event,the library should start validation

please provide a jsfiddle with steps to reproduce... you example shown above does not show that you invoke a keyevent somewhere.

**Comment by xiongsisi** [comment] 2015-10-28 10:00
as you say,i have to write validator.element as many as inputs length
and this is not what i want 
i want to trigger the validation when i first focus on the input 
what can i do but fix the library

**Comment by staabm** [comment] 2015-10-28 10:05
> as you say,i have to write validator.element as many as inputs length

what does that mean? do you intend to validate the whole form on first focus instead of one field? 



> i want to trigger the validation when i first focus on the input

with the information you provided I still dont see a bug in the library.

**Comment by staabm** [comment] 2016-02-05 20:26
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:26 UTC
Labels: NO FIDDLE
