### ISSUE TITLE
onclick validation method not only for checkboxes and radio buttons ?

### ISSUE THREAD

**Issue by ultraviolet** [jzaefferer/jquery-validation#1715] opened 2016-02-22 07:48 UTC
Issue with instant validation. 

When form field is active autosaved values are proposed (default for every form). If we choose autosaved value, by clicking on it, form field is not validated instantly, in other words error message is not removed despite value passes validation.

For example, we have a field "name" and rule of minimum 3 characters.
When we typed one character in the field, and switched to another field, field did not pass instant validation and error is populated. 

If we return to this field and type "Bob" error is removed instantly (seems like http://jqueryvalidation.org/validate#onkeyup method handles this).

But if we return to the field "name" and instead of typing erase everything and select "Bob" from proposed autosaved values, error is not removed, even if we switch to another form field (maybe http://jqueryvalidation.org/validate#onfocusout method should hadle this but it does not).    

This makes confusion in user experience, because user sees that validation is instant and errors are removed immediately after field passes validation. But in this case user selects correct value from autosaved items but error is not removed (field is not validated instantly).

There are workarounds, e.g. disable autosave for form or disable instant validation (set to false all methods except onsubmit). But how to resolve this with active instant validation?

**Comment by Arkni** [comment] 2016-02-24 14:54
Which version of this plugin do you use ?
Can you test if the master version works as expected or it behaves the same as your issue ? (just to make sure if the issue is fixed somehow or still there and should be fixed)

**Comment by ultraviolet** [comment] 2016-02-24 16:41
> Downloading the latest changes
> 
> The unreleased development files can be obtained by:
> 
>     Downloading or Forking this repository
>     Setup the build
>     Run grunt to create the built files in the "dist" directory
I suppose i need to build master version. Alas, this over my expertise. I use prepared version which i downloaded from site (jquery-validation-1.14.0.zip).

**Comment by Arkni** [comment] 2016-02-24 23:17
Here is the master version after the build (I put it on https://gist.github.com):
https://gist.githubusercontent.com/Arkni/40956198a7449d88fe0e/raw/4468022a0c984432b10284d946c26309424365eb/jquery.validate.js

**Comment by ultraviolet** [comment] 2016-02-25 10:52
> https://gist.githubusercontent.com/Arkni/40956198a7449d88fe0e/raw/4468022a0c984432b10284d946c26309424365eb/jquery.validate.js

Tried this version. Result same as described in 1st post.

**Comment by Arkni** [comment] 2016-02-26 15:37
I just followed your steps and tested them using the demo bundled withing this plugin and it's working as expected.
Here is a screen-cast of the result:
![anim](https://cloud.githubusercontent.com/assets/6888059/13356692/a4d99ed0-dc9e-11e5-8135-fcae1416c520.gif)

Maybe I'm missing something.

**Comment by ultraviolet** [comment] 2016-02-26 16:29
You are right. I get exactly same behavior. My point is that after selecting "Bob" with mouse, error remains until there is a click outside a field. This i find misleading. I think error should dissapear exactly after "Bob" is selected (no need to click outside field).

**Comment by Arkni** [comment] 2016-02-26 16:56
> I think error should dissapear exactly after "Bob" is selected (no need to click outside field).

I get it now. We can achieve that using the `input` event (>`IE9`), but `jquery-validate` only use `blur`, `focus` and `keyup` events. Maybe it's time to use this event.

//Cc @staabm

**Comment by ultraviolet** [comment] 2016-02-26 18:03
Thanks for examining this issue! Up to you to decide, whether it is worth it, especially taking into account development of new event.

**Comment by Arkni** [comment] 2016-05-05 21:39
I think this can be closed now, as the OP already fixed his issue using the work around mentioned in https://github.com/jzaefferer/jquery-validation/pull/1733#issuecomment-204176028

**Closed** 2016-05-06 17:05 UTC
Labels: Bug, Core
