### ISSUE TITLE
missing dist folder on npm package

### ISSUE THREAD

**Issue by leobalter** [jzaefferer/jquery-validation#1486] opened 2015-05-21 19:39 UTC
The dist folder isn't included on the latest version.

**Comment by Purbha** [comment] 2015-05-26 06:45
Yes :( Create dist with build setup using nodejs is kindda confusing..

**Comment by ryan-sandy** [comment] 2015-06-12 12:54
This is a duplicate of #1420.

Someone came up with a workaround.

**Comment by staabm** [comment] 2015-06-13 09:35
Closing bacause of duplicate.

**Closed by staabm** 2015-06-13 09:35 UTC
