### ISSUE TITLE
Bug on group validation

### ISSUE THREAD

**Issue by onuryildiz58** [jzaefferer/jquery-validation#1676] opened 2015-12-29 07:26 UTC
When using jQuery Validation Plugin - v1.14.0 - 6/30/2015, if you valdiate a group of items it does not look if other items are validated or not and submits form.
When using version 11 the code works.
The sample code is here: 

                            $(document).ready(function () {
                                $( "#companyform" ).validate({
                                    rules: {
                                        companyname: {
                                            require_from_group: [1,".mygroup"]
                                        },
                                        firstname: {
                                            require_from_group: [1,".mygroup"]
                                        },
                                        tel1: {
                                            required : true
                            }
                            }
                            });
                                //add require from group method
                                jQuery.validator.addMethod("require_from_group", function (value, element, options) {
                                    var validator = this;
                                    var selector = options[1];
                                    var validOrNot = $(selector, element.form).filter(function () {
                                        return validator.elementValue(this);
                                    }).length >= options[0];

                                    if (!$(element).data('being_validated')) {
                                        var fields = $(selector, element.form);
                                        fields.data('being_validated', true);
                                        fields.valid();
                                        fields.data('being_validated', false);
                                    }
                                    return validOrNot;
                                }, jQuery.format("Please fill at least {0} of these fields."));
                            });

**Comment by staabm** [comment] 2016-01-30 19:13
Could you provide a jsfiddle and describe the concrete steps to reproduce the issue?

**Comment by staabm** [comment] 2016-02-05 20:28
Closing because no repro jsfiddle availabe.
If you still experience the issue, please comment and provide a jsfiddle or other kind of simplied code sample to reproduce.

Thanks for the report.

**Closed by staabm** 2016-02-05 20:28 UTC
Labels: NO FIDDLE
