### ISSUE TITLE
Create a build of package to use via npm

### ISSUE THREAD

**Issue by randsonjs** [jzaefferer/jquery-validation#1420] opened 2015-02-27 21:28 UTC
Nowadays, I use this plugin into the directory of plugin. Installing all dependencies and generate a build with grunt.

If you put a file `dist/jquery-validation.js` and `dist/jquery-validation.min.js` in this repository. It would be great ;)

What you think about it?

**Comment by ryan-sandy** [comment] 2015-03-25 18:51
I too need this feature.

After looking at the source, the dist directory is included in npm package with a pre-publish script. However, these changes exists on they 1.13.2-pre version. It would be awesome if someone could publish this.

I

**Comment by ryan-sandy** [comment] 2015-03-25 19:01
I dug a little deeper and found that this is a duplicate of #1339.

**Comment by milotoor** [comment] 2015-05-11 21:30
@jzaefferer Do you have any plans to publish soon? I and others would greatly appreciate this!

**Comment by tbranyen** [comment] 2015-05-21 18:35
I've published a dist module on NPM, `npm install jquery-validate-dist`.  If @jzaefferer would like to take this over, please let me know.

**Comment by randsonjs** [comment] 2015-05-21 18:40
Very good @tbranyen, also will be great if it is available on bower too.

**Comment by milotoor** [comment] 2015-05-21 19:37
:+1: Thanks bunches @tbranyen

**Comment by jzaefferer** [comment] 2015-06-16 17:09
It has [been a while since `1.13.1`](https://github.com/jzaefferer/jquery-validation/compare/1.13.1...master). I'm currently doing some issue triage, will do a new release afterwards. Sorry for the long delay - this project isn't paying my bills...

**Comment by milotoor** [comment] 2015-06-16 22:08
Thanks for maintaining it at all @jzaefferer!

**Comment by jzaefferer** [comment] 2015-06-30 16:15
I just published 1.14.0 on npm. This now includes all the `dist` files.

@tbranyen thanks for the interim solution - can you mark that package as deprecated?

**Closed by jzaefferer** 2015-06-30 16:15 UTC

**Comment by denisz1** [comment] 2016-10-18 03:43
@tbranyen Please keep it because we miss `dist` folder again :(
@jzaefferer I know you have not much time for this, but it is mssing again? It break existing systems which is expecting that folder.

**Comment by uhrohraggy** [comment] 2017-03-08 17:33
This is still an issue. What's a good workaround, or for finding what package is referencing the dist folder?
