### ISSUE TITLE
JQuery Validation, call the valid method, is not call remote

### ISSUE THREAD

**Issue by lcyan** [jzaefferer/jquery-validation#1763] opened 2016-04-09 10:51 UTC
JQuery Validation, call the valid method, is not call remote, remote valid is not work.

$id_mobile.valid()

**Comment by Arkni** [comment] 2016-04-09 16:18
Please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) containing a set of reproducible steps.

**Comment by toabi** [comment] 2016-07-26 10:11
I think this might be a duplicate of https://github.com/jzaefferer/jquery-validation/issues/1045

**Comment by staabm** [comment] 2016-09-01 09:15
Agree, duplicate of #1045.

Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.

**Closed by staabm** 2016-09-01 09:15 UTC
Labels: NO FIDDLE
